#!/bin/bash

source "${GAP_DIR}/.env" 

K3S_VERSION=v1.28.3\%2Bk3s2
K3S_SELINUX_TAG="v1.4.stable.1"
K3S_SELINUX_VERSION="1.4-1"

cat << EOF >> "${GAP_DIR}/.env"
K3S_VERSION=${K3S_VERSION}
K3S_SELINUX_TAG=${K3S_SELINUX_TAG}
K3S_SELINUX_VERSION=${K3S_SELINUX_VERSION}
EOF
