#!/bin/bash

source .env

mkdir -pv ${GAP_DIR}/temp

sudo tee "${GAP_DIR}/.env" > /dev/null <<EOF
GAP_DIR=../gapfiles
OS=Linux
ARCH=x86_64
CRANE_VERSION=${CRANE_VERSION}
K3S_VERSION=${K3S_VERSION}
K3S_SELINUX_TAG=${K3S_SELINUX_TAG}
K3S_SELINUX_VERSION=${K3S_SELINUX_VERSION}
CALICO_VERSION=${CALICO_VERSION}
HELM_VERSION=${HELM_VERSION}
LONGHORN_VERSION=${LONGHORN_VERSION}
EOF
